require: rubocop-rails

Documentation:
  Enabled: false

AllCops:
 Exclude:
  - db/**/*
  - bin/**/*
  - config/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Security/Open:
  Enabled: false

Rails/FilePath:
  Enabled: false
  